"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
require("dotenv").config();
const express_1 = __importDefault(require("express"));
const database_1 = __importDefault(require("./model/database"));
const compression_1 = __importDefault(require("compression"));
const path_1 = __importDefault(require("path"));
const cors_1 = __importDefault(require("cors"));
(0, database_1.default)();
const app = (0, express_1.default)();
app.set("view engine", "ejs").set("views", "view");
app.use((0, cors_1.default)());
app.use((0, compression_1.default)());
app.use(express_1.default.json({ limit: "20mb" }));
//app.use(express.static(path.join(__dirname, "..", "clients", "dist")));
app.use(express_1.default.static(path_1.default.join(__dirname, "view")));
app.use(express_1.default.static(path_1.default.join(__dirname)));
app.use(express_1.default.urlencoded({ extended: true, limit: "25mb" }));
exports.default = app;
